name: Build application

on:
  push:
    tags: [ '*' ]
    branches: [ 'master' ]

  workflow_dispatch: {}

jobs:
  run:
    uses: milaboratory/github-ci/.github/workflows/java-gradle-lib.yaml@v1
    with:
      lib-name: MiPlots
      lib-name-slug: 'miplots'
      java-version: '11'
      build-project: ''
      notify-telegram: true
      publish-dev-tasks: |
        publishAllPublicationsToMiPrivateRepository
      publish-release-tasks: |
        publishAllPublicationsToMiPrivateRepository

    secrets:
      GRADLE_PROPERTIES: |
        miRepoAccessKeyId=${{ secrets.AWS_CI_ACCESS_KEY_ID }}
        miRepoSecretAccessKey= ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}

      AWS_KEY_ID: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
      AWS_KEY_SECRET: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}

      TELEGRAM_NOTIFICATION_TARGET: ${{ secrets.TG_CHANNEL_MIBUILDS }}
      TELEGRAM_API_TOKEN: ${{ secrets.TG_CI_BOT_TOKEN }}
